@echo off
cd /d "%~dp0"
echo Adding files...
"C:\Program Files\Git\cmd\git.exe" add .
echo Committing...
"C:\Program Files\Git\cmd\git.exe" commit -m "feat: Implement Apple Siri design aesthetic and glassmorphism"
echo Pushing...
"C:\Program Files\Git\cmd\git.exe" push
